# Robot's motion parameters
controller_server:
  ros__parameters:
    max_velocity_x: 0.5  # Max forward velocity (m/s)
    max_velocity_y: 0.0  # Max lateral velocity (m/s)
    max_angular_velocity: 0.5  # Max angular velocity (rad/s)
    min_velocity_x: 0.0
    min_velocity_y: 0.0
    min_angular_velocity: 0.0
    acc_lim_x: 1.0  # Max acceleration for forward motion (m/s^2)
    acc_lim_y: 0.0  # Max acceleration for lateral motion (m/s^2)
    acc_lim_theta: 2.0  # Max angular acceleration (rad/s^2)

# Costmap configuration
local_costmap:
  ros__parameters:
    robot_radius: 0.4  # FIND THE DIMENSIONexplorer.exe .
    
    robot_base_frame: "base_link"
    footprint: [[-0.2, -0.2], [0.2, -0.2], [0.2, 0.2], [-0.2, 0.2]]  # Footprint as a rectangle

# Global costmap (optional)
global_costmap:
  ros__parameters:
    robot_radius: 0.2
    robot_base_frame: "base_link"
    footprint: [[-0.2, -0.2], [0.2, -0.2], [0.2, 0.2], [-0.2, 0.2]]

# Path planner parameters (example)
planner_server:
  ros__parameters:
    planner_frequency: 20.0
    planner_patience: 5.0
    max_planning_attempts: 3
    max_velocity_x: 0.5  # Forward velocity during planning
    max_velocity_theta: 1.0  # Max angular velocity during planning
